---
  root: true
  rules: {}
  env:
    es6: true
    amd: true
    node: true
    browser: true
    mocha: true
  extends: "eslint:recommended"
  ecmaFeatures:
    sourceType: "module"
  parserOptions:
    sourceType: "module"
